title: h4ra's Life Journey
author: h4ra
description: A blog for the 80-year-old me.
remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

github_username: h4ra
show_excerpts: true

header_pages:
  - index.md
  - about.md
  - lessons.md

sass:
  style: compressed
