title: "h4ra's Life Journey"
author: "h4ra"
description: "Documenting my life and growth."
remote_theme: poole/hyde

# Social links
github_username: h4ra

# Layout settings
show_excerpts: true

header_pages:
  - index.md
  - about.md
  - lessons.md
