title: "h4ra's Life Journey"
author: "h4ra"
description: "A blog for the 80-year-old me. <br> [About](/about) | [Lessons](/lessons)"
remote_theme: poole/hyde

# Social links
github_username: h4ra

# Layout settings
show_excerpts: true

header_pages:
  - index.md
  - about.md
  - lessons.md

  # Hyde specific settings
sidebar_label: "h4ra"
