title: "h4ra's Life Journey"
author: "h4ra"
description: "A blog for the 80-year-old me."
remote_theme: mmistakes/jekyll-theme-basically-basic

# Social links
github_username: h4ra

# Layout settings
show_excerpts: true

header_pages:
  - index.md
  - about.md
  - lessons.md

